

const bands = [
  'AC/DC',
  'Led Zeppelin',
  'Black Sabbath',
  'Queen',
  'The Rolling Stones',
  'Pink Floyd',
  'Deep Purple',
  'Guns N\' Roses',
  'Metallica',
  'Iron Maiden',
  'Judas Priest',
  'Motörhead',
  'Kiss',
  'Aerosmith',
  'Van Halen',
  'The Who',
  'Ramones',
  'The Clash',
  'Sex Pistols',
  'Nirvana',
  'Pearl Jam',
  'Soundgarden',
  'Alice in Chains',
  'Red Hot Chili Peppers',
  'Foo Fighters',
  'Green Day',
  'The Offspring',
  'Blink-182',
  'System of a Down',
  'Rage Against the Machine',
  'Linkin Park',
  'Limp Bizkit',
  'Korn',
  'Slipknot',
  'Disturbed',
  'Avenged Sevenfold',
  'Breaking Benjamin',
  'Three Days Grace',
  'Skillet',
  'Shinedown',
  'Seether',
  'Godsmack',
  'Five Finger Death Punch',
  'Volbeat',
  'Alter Bridge',
  'Creed',
  'Nickelback',
  'Bon Jovi',
  'Def Leppard',
  'Mötley Crüe',
  'Poison',
  'Twisted Sister',
  'Scorpions',
  'Whitesnake',
  'Journey',
  'Foreigner',
  'Boston',
  'Styx',
  'Kansas',
  'Rush',
  'Yes',
  'Genesis',
  'Jethro Tull',
  'King Crimson',
  'Emerson, Lake & Palmer',
  'The Doors',
  'The Jimi Hendrix Experience',
  'Cream',
  'The Yardbirds',
  'The Kinks',
  'The Animals',
  'The Beatles',
  'The Beach Boys',
  'The Eagles',
  'Fleetwood Mac',
  'Creedence Clearwater Revival',
  'Lynyrd Skynyrd',
  'ZZ Top',
  'The Allman Brothers Band',
  'Thin Lizzy',
  'U2',
  'R.E.M.',
  'The Police',
  'The Cure',
  'The Smiths',
  'Joy Division',
  'New Order',
  'Depeche Mode',
  'The Killers',
  'Coldplay',
  'Muse',
  'Radiohead',
  'Oasis',
  'Blur',
  'Suede',
  'Pulp',
  'The Stone Roses',
  'The Verve',
  'Arctic Monkeys',
  'The Strokes',
  'The White Stripes',
  'The Black Keys',
  'Kings of Leon',
  'Queens of the Stone Age',
  'The Smashing Pumpkins',
  'Jane\'s Addiction',
  'Faith No More',
  'Tool',
  'A Perfect Circle',
  'Puscifer',
  'Primus',
  'Incubus',
  '311',
  'Sublime',
  'No Doubt',
  'Garbage',
  'The Cranberries',
  'Hole',
  'L7',
  'Babes in Toyland',
  'Veruca Salt',
  'The Breeders',
  'Pixies',
  'Sonic Youth',
  'My Bloody Valentine',
  'Slowdive',
  'Ride',
  'Chapterhouse',
  'Lush',
  'Swervedriver',
  'My Chemical Romance',
  'Fall Out Boy',
  'Panic! at the Disco',
  'Paramore',
  'Taking Back Sunday',
  'Dashboard Confessional',
  'The All-American Rejects',
  'Good Charlotte',
  'Simple Plan',
  'Sum 41',
  'Yellowcard',
  'New Found Glory',
  'Saves the Day',
  'The Get Up Kids',
  'Jimmy Eat World',
  'Weezer',
  'Cake',
  'They Might Be Giants',
  'Fountains of Wayne',
  'Everclear',
  'Lit',
  'Alien Ant Farm',
  'P.O.D.',
  'Papa Roach',
  'Hoobastank',
  'Crazy Town',
  'Puddle of Mudd',
  'Saliva',
  'Trapt',
  'Fuel',
  'Staind',
  'Drowning Pool',
  'Static-X',
  'Mudvayne',
  'Mushroomhead',
  'Powerman 5000',
  'Rob Zombie',
  'White Zombie',
  'Marilyn Manson',
  'Nine Inch Nails',
  'Ministry',
  'KMFDM',
  'Rammstein',
  'Megadeth',
  'Slayer',
  'Anthrax',
  'Testament',
  'Exodus',
  'Overkill',
  'Death Angel',
  'Sepultura',
  'Soulfly',
  'Cavalera Conspiracy',
  'Pantera',
  'Damageplan',
  'Hellyeah',
  'Lamb of God',
  'Mastodon',
  'Gojira',
  'Opeth',
  'In Flames',
  'At the Gates',
  'Dark Tranquillity',
  'Children of Bodom',
  'Arch Enemy',
  'Amon Amarth',
  'Ensiferum',
  'Wintersun',
  'Finntroll',
  'Korpiklaani',
  'Turisas',
  'Moonsorrow',
  'Eluveitie',
  'Nightwish',
  'Within Temptation',
  'Epica',
  'Lacuna Coil',
  'Evanescence',
  'Halestorm',
  'The Pretty Reckless',
  'In This Moment',
  'Flyleaf',
  'Kittie',
  'Arch Enemy',
  'Jinjer',
  'Spiritbox',
  'Poppy',
  'Bring Me the Horizon',
  'Asking Alexandria',
  'Attack Attack!',
  'Of Mice & Men',
  'Sleeping with Sirens',
  'Pierce the Veil',
  'A Day to Remember',
  'I Prevail',
  'Beartooth',
  'Wage War',
  'Motionless in White',
  'Ice Nine Kills',
  'Bad Omens',
  'Sleep Token',
  'Ghost',
  'Greta Van Fleet',
  'The Struts',
  'Dirty Honey',
  'Rival Sons',
  'The Glorious Sons',
  'Crown Lands',
  'Royal Blood',
  'Highly Suspect',
  'Badflower',
  'Dorothy',
  'Starcrawler',
  'The Warning',
  'Maneskin',
];

export default bands;
